<?php

namespace App\Console\Commands\Downloads;

use App\Console\Commands\Components\getProductsTrait;
use Illuminate\Console\Command;

class BgHlapetaProducts extends Command
{
    use getProductsTrait;
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:bghlapeta-products';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Download bg hlapeta products';

    /**
     * Execute the console command.
     */

    public function handle()
    {
        $categoryLinks = [
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/maketi-za-sglobyavane/avtomobili?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/maketi-za-sglobyavane/aksesoari-2015-10-06?page=',
            'https://bghlapeta.com/cats/akumulatorni-koli-dzhipove-motori-i-bagita/aksesoari?page=',
            'https://bghlapeta.com/cats/gradina/ploshtadki-za-igra/akcecoari-za-fungoo?page=',
            'https://bghlapeta.com/cats/stolcheta-i-aksesoari-za-hranene/aksesoari-za-mama?page=',
            'https://bghlapeta.com/cats/stolcheta-i-koshnitza-za-kola/akcecoari-za-ctolcheta?page=',
            'https://bghlapeta.com/cats/gradina/akcecoari-za-tramplini-i-batuti?page=',
            'https://bghlapeta.com/cats/vani-korita-i-aksesoari-higiena-i-banya/aksesoari-higiena-i-banya?page=',
            'https://bghlapeta.com/cats/detski-kolichki-i-aksesoari-za-razhodka/aksesoari-za-kolichki?page=',
            'https://bghlapeta.com/cats/aktivna-gimnastika-shezlong-i-lyulki/aktivna-gimnastika?page=',
            'https://bghlapeta.com/cats/akumulatorni-koli-dzhipove-motori-i-bagita/akumulatorni-bagita?page=',
            'https://bghlapeta.com/cats/akumulatorni-koli-dzhipove-motori-i-bagita/akumulatorni-dzhipove?page=',
            'https://bghlapeta.com/cats/akumulatorni-koli-dzhipove-motori-i-bagita/akumulatorni-kamioni-i-traktori?page=',
            'https://bghlapeta.com/cats/akumulatorni-koli-dzhipove-motori-i-bagita/akumulatorni-motori?page=',
            'https://bghlapeta.com/cats/akumulatorni-koli-dzhipove-motori-i-bagita/akumulatorni-koli?page=',
            'https://bghlapeta.com/cats/stolcheta-i-koshnitza-za-kola/bazi-za-stolcheta?page=',
            'https://bghlapeta.com/cats/koshari-za-spane-i-igra-aksesoari-za-san/baldaxini-i-ctoiki?page=',
            'https://bghlapeta.com/cats/gradina/baceini?page=',
            'https://bghlapeta.com/cats/gradina/baceini/baceini-c-naduvaem-bord?page=',
            'https://bghlapeta.com/cats/igrachki/prikazni-filmovi-i-super-geroi/batman?page=',
            'https://bghlapeta.com/cats/igrachki/kukli-i-aksesoari/bebeta-kukli-i-dreshki?page=',
            'https://bghlapeta.com/cats/koshari-za-spane-i-igra-aksesoari-za-san/bebefoni?page=',
            'https://bghlapeta.com/cats/uredi-za-doma/bebefoni-2014-09-20?page=',
            'https://bghlapeta.com/cats/koshari-za-spane-i-igra-aksesoari-za-san/bebeshko-koshche?page=',
            'https://bghlapeta.com/cats/stolcheta-i-aksesoari-za-hranene/belyoo-za-bremenni-i-karmachki?page=',
            'https://bghlapeta.com/cats/stolcheta-i-aksesoari-za-hranene/biberoni?page=',
            'https://bghlapeta.com/cats/koshari-za-spane-i-igra-aksesoari-za-san/bebeshki-legla-blizo-do-men?page=',
            'https://bghlapeta.com/cats/prohodilki-i-bandzhi/bandzhi?page=',
            'https://bghlapeta.com/cats/prohodilki-i-bandzhi/bandzhi-gashti?page=',
            'https://bghlapeta.com/cats/vani-korita-i-aksesoari-higiena-i-banya/vani-i-korita?page=',
            'https://bghlapeta.com/cats/uredi-za-doma/vezni-i-kantari?page=',
            'https://bghlapeta.com/cats/igrachki/prikazni-filmovi-i-super-geroi/velikolepnata-shestorka?page=',
            'https://bghlapeta.com/cats/igrachki/prevozni-sredstva-pisti-i-garazh/vlakove-i-traseta?page=',
            'https://bghlapeta.com/cats/lyato-plazh-i-more/vodni-pistoleti?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/banbao/voenna-zashtita?page=',
            'https://bghlapeta.com/cats/stolcheta-i-aksesoari-za-hranene/v-zglavnici-za-bremenni-i-k-rmene?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/maketi-za-sglobyavane/voenna-tehnika?page=',
            'https://bghlapeta.com/cats/koshari-za-spane-i-igra-aksesoari-za-san/v-zglavnichki?page=',
            'https://bghlapeta.com/cats/stolcheta-i-koshnitza-za-kola/v-zglavnichki-za-p-t?page=',
            'https://bghlapeta.com/cats/koshari-za-spane-i-igra-aksesoari-za-san/v-rtelezhki-i-igrachki-za-krevatche?page=',
            'https://bghlapeta.com/cats/koshari-za-spane-i-igra-aksesoari-za-san/gnezda?page=',
            'https://bghlapeta.com/cats/stolcheta-i-aksesoari-za-hranene/grizalki?page=',
            'https://bghlapeta.com/cats/stolcheta-i-koshnitza-za-kola/grupa-0-0-13-kg?page=',
            'https://bghlapeta.com/cats/stolcheta-i-koshnitza-za-kola/grupa-0-1-0-18-kg?page=',
            'https://bghlapeta.com/cats/stolcheta-i-koshnitza-za-kola/grupa-0-1-2-3-0-36-kg-817925460?page=',
            'https://bghlapeta.com/cats/stolcheta-i-koshnitza-za-kola/grupa-1-9-18-kg?page=',
            'https://bghlapeta.com/cats/stolcheta-i-koshnitza-za-kola/grupa-1-2-9-25-kg?page=',
            'https://bghlapeta.com/cats/stolcheta-i-koshnitza-za-kola/grupa-1-2-3-9-36-kg?page=',
            'https://bghlapeta.com/cats/stolcheta-i-koshnitza-za-kola/grupa-2-3-15-36-kg?page=',
            'https://bghlapeta.com/cats/vani-korita-i-aksesoari-higiena-i-banya/garneta-i-sedalki-za-toaletna?page=',
            'https://bghlapeta.com/cats/gradina/baceini/naduvaemi-baseini?page=',
            'https://bghlapeta.com/cats/lyato-plazh-i-more/detcki-baceini?page=',
            'https://bghlapeta.com/cats/stolcheta-i-koshnitza-za-kola/detski-kufari-i-aksesoari-za-pat?page=',
            'https://bghlapeta.com/cats/igrachki/komplekti-za-momcheta/detski-orazhiya-i-hobi?page=',
            'https://bghlapeta.com/cats/gradina/baceini/dzhakuzi?page=',
            'https://bghlapeta.com/cats/stolcheta-i-aksesoari-za-hranene/dozatori-i-kutii-za-cuxo-mlyako?page=',
            'https://bghlapeta.com/cats/igrachki/komplekti-za-momicheta/domakinski-uredi-i-pochistvashti-tzentrove?page=',
            'https://bghlapeta.com/cats/igrachki/prikazni-filmovi-i-super-geroi/dora-izsledovatelkata?page=',
            'https://bghlapeta.com/cats/igrachki/prikazni-filmovi-i-super-geroi/drakoni-i-dinozavri?page=',
            'https://bghlapeta.com/cats/igrachki/igrachki-s-ditantzionno/samoleti-i-helikopteri-s-distantzionno?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/konstruktori-i-pazeli?page=',
            'https://bghlapeta.com/cats/uredi-za-doma/drugi-uredi?page=',
            'https://bghlapeta.com/cats/detski-kolichki-i-aksesoari-za-razhodka/dazhdobrani-za-kolichki?page=',
            'https://bghlapeta.com/cats/igrachki/darveni-igrachki/darveni-zanimatelni-i-obrazovatelni-igrachki?page=',
            'https://bghlapeta.com/cats/igrachki/darveni-igrachki/darveni-igrachki-za-momicheta?page=',
            'https://bghlapeta.com/cats/igrachki/darveni-igrachki?page=',
            'https://bghlapeta.com/cats/igrachki/darveni-igrachki/darveni-igrachki-za-momcheta?page=',
            'https://bghlapeta.com/cats/igrachki/darveni-igrachki/darveni-igrachki-za-nai-malkite?page=',
            'https://bghlapeta.com/cats/koshari-za-spane-i-igra-aksesoari-za-san/koshari-za-spane-i-igra?page=',
            'https://bghlapeta.com/cats/gradina/ploshtadki-za-igra/d-rveni-kuli-c-p-rzalka?page=',
            'https://bghlapeta.com/cats/gradina/ploshtadki-za-igra/d-rveni-k-shi-c-p-rzalka?page=',
            'https://bghlapeta.com/cats/igrachki/darveni-igrachki/darveni-muzikalni-instrumenti?page=',
            'https://bghlapeta.com/cats/igrachki/test-igrachki/darveni-pazeli?page=',
            'https://bghlapeta.com/cats/igrachki/darveni-igrachki/darveni-pazeli-i-konstruktori?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/banbao/eko-ferma?page=',
            'https://bghlapeta.com/cats/detski-kolichki-i-aksesoari-za-razhodka/ergonomichna-ranica-za-bebe?page=',
            'https://bghlapeta.com/cats/igrachki/muzikalni-logicheski-i-zanimatelni-igrachki-i-igri?page=',
            'https://bghlapeta.com/cats/stolcheta-i-aksesoari-za-hranene/zalagalki-chesalki-i-grizalki-za-zabki?page=',
            'https://bghlapeta.com/cats/igrachki/prikazni-filmovi-i-super-geroi/zamraznaloto-kralstvo?page=',
            'https://bghlapeta.com/cats/igrachki/bebeshki-igrachki/lyulka-za-vkashti?page=',
            'https://bghlapeta.com/cats/igrachki/muzikalni-logicheski-i-zanimatelni-igrachki-i-igri/zanimatelni-igri?page=',
            'https://bghlapeta.com/cats/igrachki/bebeshki-igrachki/igrachki-za-banya?page=',
            'https://bghlapeta.com/cats/vani-korita-i-aksesoari-higiena-i-banya/igrachki-za-banya-2014-09-18-?page=',
            'https://bghlapeta.com/cats/igrachki/bebeshki-igrachki/igrachki-za-kola?page=',
            'https://bghlapeta.com/cats/igrachki/bebeshki-igrachki/igrachki-za-kolichki?page=',
            'https://bghlapeta.com/cats/igrachki/bebeshki-igrachki/igrachki-za-krevatcheta?page=',
            'https://bghlapeta.com/cats/igrachki/bebeshki-igrachki?page=',
            'https://bghlapeta.com/cats/stolcheta-i-koshnitza-za-kola/igrachki-za-p-t?page=',
            'https://bghlapeta.com/cats/detski-kolichki-i-aksesoari-za-razhodka/podlozhki-za-kolichki?page=',
            'https://bghlapeta.com/cats/igrachki/igrachki-s-ditantzionno?page=',
            'https://bghlapeta.com/cats/trikolki-i-karting-s-pedali/igrachki-s-pedali?page=',
            'https://bghlapeta.com/cats/igrachki/interaktivni-i-razkazvachi-na-prikazki?page=',
            'https://bghlapeta.com/cats/uredi-za-doma/inhalatori?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/maketi-za-sglobyavane/kamioni?page=',
            'https://bghlapeta.com/cats/uredi-za-doma/ionizatori-i-ovlazhniteli-za-vazduh?page=',
            'https://bghlapeta.com/cats/igrachki/prevozni-sredstva-pisti-i-garazh/prevozni-sredstva?page=',
            'https://bghlapeta.com/cats/igrachki/igrachki-s-ditantzionno/kamioni-i-traktori-s-distantzionno?page=',
            'https://bghlapeta.com/cats/trikolki-i-karting-s-pedali/karting?page=',
            'https://bghlapeta.com/cats/velosipedi-i-kolela-za-balans/kaski-i-protektori?page=',
            'https://bghlapeta.com/cats/trotinetki-skeitbord-i-roleri/kaski?page=',
            'https://bghlapeta.com/cats/detski-kolichki-i-aksesoari-za-razhodka/kengugu?page=',
            'https://bghlapeta.com/cats/igrachki/bebeshki-igrachki/kilimcheta-za-igra?page=',
            'https://bghlapeta.com/cats/vani-korita-i-aksesoari-higiena-i-banya/kozmetika-za-bebeta?page=',
            'https://bghlapeta.com/cats/stolcheta-i-koshnitza-za-kola/kolani-za-bezopacnoct?page=',
            'https://bghlapeta.com/cats/prohodilki-i-bandzhi/kolani-za-prohozhdane?page=',
            'https://bghlapeta.com/cats/igrachki/kukli-i-aksesoari/kolektzii-kukli?page=',
            'https://bghlapeta.com/cats/igrachki/prevozni-sredstva-pisti-i-garazh/kolektzionerski-i-metalni-kolichki?page=',
            'https://bghlapeta.com/cats/velosipedi-i-kolela-za-balans/velosipedi?page=',
            'https://bghlapeta.com/cats/koli-za-izbutvane-koncheta-za-yazdene-i-lyulki/koli-za-izbutvane?page=',
            'https://bghlapeta.com/cats/velosipedi-i-kolela-za-balans/kolela-za-balans?page=',
            'https://bghlapeta.com/cats/detski-kolichki-i-aksesoari-za-razhodka/kolichki-za-bliznatzi?page=',
            'https://bghlapeta.com/cats/igrachki/kukli-i-aksesoari/kolichki-za-kukli?page=',
            'https://bghlapeta.com/cats/igrachki/igrachki-s-ditantzionno/kolichki-i-dzhipove-s-distantzionno?page=',
            'https://bghlapeta.com/cats/igrachki/prevozni-sredstva-pisti-i-garazh/kolichki-dzhipove-i-motori?page=',
            'https://bghlapeta.com/cats/detski-kolichki-i-aksesoari-za-razhodka/kombinirani-kolichki?page=',
            'https://bghlapeta.com/cats/igrachki/komplekti-za-momicheta?page=',
            'https://bghlapeta.com/cats/igrachki/komplekti-za-momcheta?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/banbao?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/konctruktori-engino?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/konstruktori-lego?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/konstruktori-mega-bloks?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/konstruktori-playmobil?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki?page=',
            'https://bghlapeta.com/cats/stolcheta-i-aksesoari-za-hranene/termochanti-za-hrani-i-shisheta?page=',
            'https://bghlapeta.com/cats/koli-za-izbutvane-koncheta-za-yazdene-i-lyulki/koncheta-za-yazdene?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/maketi-za-sglobyavane/korabi?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/banbao/kosmos?page=',
            'https://bghlapeta.com/cats/vani-korita-i-aksesoari-higiena-i-banya/kofi-i-c-dove-za-izplakvane?page=',
            'https://bghlapeta.com/cats/igrachki/prikazni-filmovi-i-super-geroi/kostenurkite-nindzha?page=',
            'https://bghlapeta.com/cats/vani-korita-i-aksesoari-higiena-i-banya/kosh-za-pamperci?page=',
            'https://bghlapeta.com/cats/koshari-za-spane-i-igra-aksesoari-za-san/koshari-za-igra?page=',
            'https://bghlapeta.com/cats/detski-kolichki-i-aksesoari-za-razhodka/koshove-za-novorodeno?page=',
            'https://bghlapeta.com/cats/igrachki/prevozni-sredstva-pisti-i-garazh/kranove-traktori-i-bageri?page=',
            'https://bghlapeta.com/cats/igrachki/kukli-i-aksesoari/kukli-za-kuklen-teatar?page=',
            'https://bghlapeta.com/cats/igrachki/kukli-i-aksesoari?page=',
            'https://bghlapeta.com/cats/stolcheta-i-aksesoari-za-hranene/kutii-i-klipcove?page=',
            'https://bghlapeta.com/cats/igrachki/komplekti-za-momicheta/kuhni-i-pribori?page=',
            'https://bghlapeta.com/cats/gradina/kashti-za-igra?page=',
            'https://bghlapeta.com/cats/sheini-ski-i-zimni-sportove/kanki-za-led?page=',
            'https://bghlapeta.com/cats/gradina/kashti-za-igra?page=',
            'https://bghlapeta.com/cats/igrachki/kukli-i-aksesoari/kashti-i-obzavezhdane-za-kukli?page=',
            'https://bghlapeta.com/cats/igrachki/muzikalni-logicheski-i-zanimatelni-igrachki-i-igri/laboratorii?page=',
            'https://bghlapeta.com/cats/koshari-za-spane-i-igra-aksesoari-za-san/legla?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/maketi-za-sglobyavane/samoleti?page=',
            'https://bghlapeta.com/cats/detski-kolichki-i-aksesoari-za-razhodka/letni-kolichki?page=',
            'https://bghlapeta.com/cats/stolcheta-i-aksesoari-za-hranene/ligavnici?page=',
            'https://bghlapeta.com/cats/lyato-plazh-i-more/lodki?page=',
            'https://bghlapeta.com/cats/igrachki/igrachki-s-ditantzionno/lodki-s-distantzionno?page=',
            'https://bghlapeta.com/cats/koli-za-izbutvane-koncheta-za-yazdene-i-lyulki/lyulki-2013-10-08?page=',
            'https://bghlapeta.com/cats/gradina/l-1?page=',
            'https://bghlapeta.com/cats/aktivna-gimnastika-shezlong-i-lyulki/lyulki?page=',
            'https://bghlapeta.com/cats/igrachki/muzikalni-logicheski-i-zanimatelni-igrachki-i-igri/daski-za-risuvane-chinove-i-masi?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/magnitni-konstruktori?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/konstruktori-teifoc?page=',
            'https://bghlapeta.com/cats/koshari-za-spane-i-igra-aksesoari-za-san/maci-ctolcheta-etazherki-i-akcecoari?page=',
            'https://bghlapeta.com/cats/gradina/masichki-stolcheta-i-peiki?page=',
            'https://bghlapeta.com/cats/koshari-za-spane-i-igra-aksesoari-za-san/matratzi-podmatrachni-ramki-i-protektori?page=',
            'https://bghlapeta.com/cats/igrachki/prikazni-filmovi-i-super-geroi/masha-i-mechoka?page=',
            'https://bghlapeta.com/cats/koshari-za-spane-i-igra-aksesoari-za-san/mebeli-i-obzavezhdane?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/metalni-konstruktori-eitech?page=',
            'https://bghlapeta.com/cats/igrachki/muzikalni-logicheski-i-zanimatelni-igrachki-i-igri/mikrofoni-i-muzikalni-instrumenti?page=',
            'https://bghlapeta.com/cats/igrachki/kukli-i-aksesoari/mini-i-zhivotni-kukli?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/maketi-za-sglobyavane/mini-figuri?page=',
            'https://bghlapeta.com/cats/igrachki/prikazni-filmovi-i-super-geroi/minyoonite?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/banbao/misiya-orel?page=',
            'https://bghlapeta.com/cats/igrachki/bebeshki-igrachki/mislene-i-koordinatziya?page=',
            'https://bghlapeta.com/cats/igrachki/kukli-i-aksesoari/modeli-za-prichecki?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/banbao/moderen-grad?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/banbao/moderen-plazh?page=',
            'https://bghlapeta.com/cats/gradina/ploshtadki-za-igra/moduli-za-razshirenie?page=',
            'https://bghlapeta.com/cats/igrachki/muzikalni-logicheski-i-zanimatelni-igrachki-i-igri/mozaiki?page=',
            'https://bghlapeta.com/cats/detski-kolichki-i-aksesoari-za-razhodka/mrezha-za-komari-za-kolichki-2014-09-15-?page=',
            'https://bghlapeta.com/cats/igrachki/igrachki-s-ditantzionno/motori-i-bagita-s-distantzionno?page=',
            'https://bghlapeta.com/cats/stolcheta-i-aksesoari-za-hranene/mrezha-za-plodove-355286255?page=',
            'https://bghlapeta.com/cats/igrachki/bebeshki-igrachki/mislene-i-kordinatziya?page=',
            'https://bghlapeta.com/cats/stolcheta-i-aksesoari-za-hranene/uredi-za-zatoplyane-na-shisheta?page=',
            'https://bghlapeta.com/cats/lyato-plazh-i-more/naduvaemi-dyushetzi?page=',
            'https://bghlapeta.com/cats/lyato-plazh-i-more/naduvaemi-igrachki?page=',
            'https://bghlapeta.com/cats/gradina/naduvaemi-tzentrove?page=',
            'https://bghlapeta.com/cats/igrachki/muzikalni-logicheski-i-zanimatelni-igrachki-i-igri/nastolni-igri?page=',
            'https://bghlapeta.com/cats/ranitzi-dreshki-i-obuvki/nececeri?page=',
            'https://bghlapeta.com/novi?page=',
            'https://bghlapeta.com/cats/koshari-za-spane-i-igra-aksesoari-za-san/noshtni-lampi?page=',
            'https://bghlapeta.com/cats/uredi-za-doma/obezopasitelni-aksesoari?page=',
            'https://bghlapeta.com/cats/koshari-za-spane-i-igra-aksesoari-za-san/obikolnici?page=',
            'https://bghlapeta.com/cats/igrachki/muzikalni-logicheski-i-zanimatelni-igrachki-i-igri/obrazovanie-i-nauka?page=',
            'https://bghlapeta.com/cats/stolcheta-i-koshnitza-za-kola/ogledalala-za-nablyudenie?page=',
            'https://bghlapeta.com/cats/koshari-za-spane-i-igra-aksesoari-za-san/odeyala?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/banbao/hai-teh?page=',
            'https://bghlapeta.com/cats/gradina/palatki?page=',
            'https://bghlapeta.com/cats/igrachki/kukli-i-aksesoari/partzaleni-kukli?page=',
            'https://bghlapeta.com/cats/koshari-za-spane-i-igra-aksesoari-za-san/peleni?page=',
            'https://bghlapeta.com/cats/igrachki/prevozni-sredstva-pisti-i-garazh/pisti-i-garazhi?page=',
            'https://bghlapeta.com/cats/igrachki/muzikalni-logicheski-i-zanimatelni-igrachki-i-igri/plastelin-i-modelin?page=',
            'https://bghlapeta.com/cats/gradina/detski-ploshtadki-i-katerushki?page=',
            'https://bghlapeta.com/cats/igrachki/bebeshki-igrachki/plyusheni-i-meki-bebeshki-igrachki?page=',
            'https://bghlapeta.com/cats/gradina/ploshtadki-za-igra?page=',
            'https://bghlapeta.com/cats/igrachki/meki-i-plyusheni-igrachki?page=',
            'https://bghlapeta.com/cats/detski-kolichki-i-aksesoari-za-razhodka/podlozhki-za-kolichka?page=',
            'https://bghlapeta.com/cats/stolcheta-i-koshnitza-za-kola/podlozhki-za-koshnici-i-ctolcheta?page=',
            'https://bghlapeta.com/cats/vani-korita-i-aksesoari-higiena-i-banya/podlozhki-i-shkafove-za-povivane?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/banbao/pozharna?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/banbao/dinastiya-tan?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/banbao/politziya?page=',
            'https://bghlapeta.com/cats/stolcheta-i-aksesoari-za-hranene/pompi-za-k-rma-178634928?page=',
            'https://bghlapeta.com/cats/gradina/baceini/pompi-za-naduvane-i-akcecoari-za-bacein?page=',
            'https://bghlapeta.com/cats/lyato-plazh-i-more/pompi-za-naduvane?page=',
            'https://bghlapeta.com/cats/vani-korita-i-aksesoari-higiena-i-banya/podlozhki-i-stolcheta-za-vani?page=',
            'https://bghlapeta.com/cats/lyato-plazh-i-more/aksesoari-za-pluvane?page=',
            'https://bghlapeta.com/cats/uredi-za-doma/praxocmukachki-roboti?page=',
            'https://bghlapeta.com/cats/igrachki/bebeshki-igrachki/prevozni-credctva-i-zanimatelni-igrachki?page=',
            'https://bghlapeta.com/cats/igrachki/prevozni-sredstva-pisti-i-garazh?page=',
            'https://bghlapeta.com/cats/uredi-za-doma/predpazna-pregrada?page=',
            'https://bghlapeta.com/cats/koshari-za-spane-i-igra-aksesoari-za-san/predpaziteli-za-leglo?page=',
            'https://bghlapeta.com/cats/stolcheta-i-aksesoari-za-hranene/pribori-i-sadove-za-hranene?page=',
            'https://bghlapeta.com/cats/stolcheta-i-aksesoari-za-hranene/pribori-za-xranene?page=',
            'https://bghlapeta.com/cats/igrachki/prikazni-filmovi-i-super-geroi?page=',
            'https://bghlapeta.com/cats?page=',
            'https://bghlapeta.com/promocii?page=',
            'https://bghlapeta.com/cats/stolcheta-i-koshnitza-za-kola/protektori-i-organaizeri?page=',
            'https://bghlapeta.com/cats/koshari-za-spane-i-igra-aksesoari-za-san/protektori-i-chershafi?page=',
            'https://bghlapeta.com/cats/igrachki/komplekti-za-momicheta/profesii-magazini-i-kasovi-aparati?page=',
            'https://bghlapeta.com/cats/igrachki/komplekti-za-momcheta/profesii-rabotilnitzi-i-instrumenti?page=',
            'https://bghlapeta.com/cats/prohodilki-i-bandzhi/prohodilki?page=',
            'https://bghlapeta.com/cats/prohodilki-i-bandzhi/prohodilki-za-butane?page=',
            'https://bghlapeta.com/cats/igrachki/test-igrachki?page=',
            'https://bghlapeta.com/cats/igrachki/test-igrachki/pazeli-nad-3-godini?page=',
            'https://bghlapeta.com/cats/igrachki/test-igrachki/pazeli-nad-8-godini?page=',
            'https://bghlapeta.com/cats/gradina/parzalki?page=',
            'https://bghlapeta.com/cats/lyato-plazh-i-more/pyasachni-igrachki?page=',
            'https://bghlapeta.com/cats/gradina/pyasachnitzi-za-igra?page=',
            'https://bghlapeta.com/cats/igrachki/bebeshki-igrachki/ramki-otlivki-i-otpechatatzi?page=',
            'https://bghlapeta.com/cats/ranitzi-dreshki-i-obuvki/ranitzi-za-detska-gradina?page=',
            'https://bghlapeta.com/cats/ranitzi-dreshki-i-obuvki/ranitzi-za-uchilishte/ranitzi-za-momicheta?page=',
            'https://bghlapeta.com/cats/ranitzi-dreshki-i-obuvki/ranitzi-za-uchilishte/ranitzi-za-momcheta?page=',
            'https://bghlapeta.com/cats/ranitzi-dreshki-i-obuvki/ranitzi-za-uchilishte?page=',
            'https://bghlapeta.com/cats/igrachki/muzikalni-logicheski-i-zanimatelni-igrachki-i-igri/risuvane-i-otzvetyavane?page=',
            'https://bghlapeta.com/cats/igrachki/komplekti-za-momcheta/roboti-trancform-ri?page=',
            'https://bghlapeta.com/cats/trotinetki-skeitbord-i-roleri/roleri?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/banbao/safari?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/banbao/svatben-svyat?page=',
            'https://bghlapeta.com/cats/koshari-za-spane-i-igra-aksesoari-za-san/sgavaemi-koshari-za-spane-i-igra?page=',
            'https://bghlapeta.com/cats/stolcheta-i-koshnitza-za-kola/cedalki-za-kola?page=',
            'https://bghlapeta.com/cats/vani-korita-i-aksesoari-higiena-i-banya/cedalki-za-toaletna?page=',
            'https://bghlapeta.com/cats/stolcheta-i-koshnitza-za-kola/cennici-i-tabeli-za-ct-klata?page=',
            'https://bghlapeta.com/cats/trotinetki-skeitbord-i-roleri/skeitbord?page=',
            'https://bghlapeta.com/cats/detski-kolichki-i-aksesoari-za-razhodka/sling-shalove?page=',
            'https://bghlapeta.com/cats/igrachki/prikazni-filmovi-i-super-geroi/spaidermen?page=',
            'https://bghlapeta.com/cats/koshari-za-spane-i-igra-aksesoari-za-san/cpalni-chuvalcheta?page=',
            'https://bghlapeta.com/cats/igrachki/sportni-igri?page=',
            'https://bghlapeta.com/cats/uredi-za-doma/sterilizatori?page=',
            'https://bghlapeta.com/cats/stolcheta-i-aksesoari-za-hranene/sterilizatori-za-shisheta-2014-09-18?page=',
            'https://bghlapeta.com/cats/vani-korita-i-aksesoari-higiena-i-banya/ctoiki?page=',
            'https://bghlapeta.com/cats/stolcheta-i-aksesoari-za-hranene/stolcheta-za-hranene?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/banbao/stroiteli?page=',
            'https://bghlapeta.com/cats/vani-korita-i-aksesoari-higiena-i-banya/ct-pala?page=',
            'https://bghlapeta.com/cats/igrachki/prikazni-filmovi-i-super-geroi/supermen?page=',
            'https://bghlapeta.com/cats/stolcheta-i-aksesoari-za-hranene/c-dove-za-xranene?page=',
            'https://bghlapeta.com/cats/stolcheta-i-aksesoari-za-hranene/cushilnici?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/banbao/sastezatelni-koli?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/banbao/sashtestva?page=',
            'https://bghlapeta.com/cats/detski-kolichki-i-aksesoari-za-razhodka/tekctil-za-kolichka?page=',
            'https://bghlapeta.com/cats/koshari-za-spane-i-igra-aksesoari-za-san/tekstil-za-krevatche?page=',
            'https://bghlapeta.com/cats/stolcheta-i-aksesoari-za-hranene/termobokcove?page=',
            'https://bghlapeta.com/cats/uredi-za-doma/termometri?page=',
            'https://bghlapeta.com/cats/stolcheta-i-aksesoari-za-hranene/termoci?page=',
            'https://bghlapeta.com/cats/igrachki/komplekti-za-momicheta/toaletki-i-aksesoari-za-krasota?page=',
            'https://bghlapeta.com/cats/gradina/tramplini-i-batuti?page=',
            'https://bghlapeta.com/top?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/banbao/prevozni-sredstva-2015-10-12?page=',
            'https://bghlapeta.com/cats/trikolki-i-karting-s-pedali/trikolki?page=',
            'https://bghlapeta.com/cats/trikolki-i-karting-s-pedali/trikolki-bez-roditelcki-kontrol?page=',
            'https://bghlapeta.com/cats/trotinetki-skeitbord-i-roleri/trotinetki?page=',
            'https://bghlapeta.com/cats/detski-kolichki-i-aksesoari-za-razhodka/ranitza-za-nosene-na-dete?page=',
            'https://bghlapeta.com/cats/uredi-za-doma/uredi-za-gotvene-2014-09-20-?page=',
            'https://bghlapeta.com/cats/stolcheta-i-aksesoari-za-hranene/uredi-za-gotvene?page=',
            'https://bghlapeta.com/cats/uredi-za-doma/uredi-za-podgryavane?page=',
            'https://bghlapeta.com/cats/trotinetki-skeitbord-i-roleri/xov-rbord-i-elektrichecki-ckuteri?page=',
            'https://bghlapeta.com/cats/vani-korita-i-aksesoari-higiena-i-banya/xavlii?page=',
            'https://bghlapeta.com/cats/igrachki/kukli-i-aksesoari/tzentrove-za-bebeta-kukli?page=',
            'https://bghlapeta.com/cats/detski-kolichki-i-aksesoari-za-razhodka/chadari?page=',
            'https://bghlapeta.com/cats/detski-kolichki-i-aksesoari-za-razhodka/chanti-i-ranitzi?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/banbao/cherniyat-mech?page=',
            'https://bghlapeta.com/cats/stolcheta-i-aksesoari-za-hranene/sushilki-i-aksesoari-za-shisheta-i-chashi?page=',
            'https://bghlapeta.com/cats/detski-kolichki-i-aksesoari-za-razhodka/chuvalcheta-za-kolichki-2014-09-15-?page=',
            'https://bghlapeta.com/cats/detski-kolichki-i-aksesoari-za-razhodka/shacita?page=',
            'https://bghlapeta.com/cats/aktivna-gimnastika-shezlong-i-lyulki/shezlong?page=',
            'https://bghlapeta.com/cats/sheini-ski-i-zimni-sportove/sheini?page=',
            'https://bghlapeta.com/cats/stolcheta-i-aksesoari-za-hranene/biberoni-i-shisheta-za-hranene-2014-09-18?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/maketi-za-sglobyavane/star-wars?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/maketi-za-sglobyavane/avtomobili?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/maketi-za-sglobyavane/aksesoari-2015-10-06?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/maketi-za-sglobyavane/voenna-tehnika?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/maketi-za-sglobyavane/kamioni?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/maketi-za-sglobyavane/mini-figuri?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/maketi-za-sglobyavane/samoleti?page=',
            'https://bghlapeta.com/cats/igrachki/konstruktori-pazeli-i-mozaiki/maketi-za-sglobyavane/korabi?page=',
        ];

        $i = true;
        foreach ($categoryLinks as $link){
            $k = 1;
            $i = true;
            while ($i == true){
                echo "+++++++++++++++++++++++++++++++".$link. '   '.$k."\n";

                $i =  $this->getProducts($link.$k,'/<h4><a href="(\S*)"/ms', 10,"" );
                $k++;
//                echo $k."\n";
            }

        }
        $this->parseData(10, 'bghlapeta');

    }




}
